# Action to test that listed tour codes can be parsed by Showdown

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the "main" branch, or any pull request events
  push:
    branches: [ "main" ]
  pull_request:
      types: [ opened, synchronize, reopened ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout OTC
        uses: actions/checkout@v3

      # Checkout Showdown
      - name: Checkout Pokemon Showdown
        uses: actions/checkout@v3
        with:
          repository: smogon/pokemon-showdown
          path: pokemon-showdown

      # Install Node
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Install actions/core
      - name: Install actions/core
        run: npm install @actions/core

      # Install actions/github
      - name: Install actions/github
        run: npm install @actions/github

      # Generate custom battle tests for Showdown 
      - name: Generate Showdown Custom Tests
        run: node $GITHUB_WORKSPACE/test/create-custom-tests.js
        working-directory: test

      # Inject custom battle test into Showdown
      - name: Inject Showdown Custom Tests
        run: |
          echo Injecting custom tests...
          cp $GITHUB_WORKSPACE/test/operationtourcode.js /home/runner/work/OTC/OTC/pokemon-showdown/test/sim/misc/operationtourcode.js
          echo Finished injecting custom tests

      # Install mocha
      - name: Install mocha
        run: npm install -g mocha@10.2.0

      # Execute custom battle tests
      - name: Run Showdown Custom Tests
        run: npx mocha -g "OperationTourCode"
        working-directory: /home/runner/work/OTC/OTC/pokemon-showdown